# Generated by Django 5.2 on 2025-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bank_created_at_bank_created_by_bank_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='client_name',
        ),
    ]
