# Generated by Django 5.2 on 2025-04-18 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_loan_client_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='installments_qt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client'], name='api_loan_client__bbe0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['bank'], name='api_loan_bank_id_03e16b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'bank'], name='api_loan_client__256657_idx'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='api.loan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan_installment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.loaninstallment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan_installment'], name='api_payment_loan_in_d17b06_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='api_payment_payment_d80323_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan'], name='api_loanins_loan_id_bd21b0_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['status', 'loan'], name='api_loanins_status_25c5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date'], name='api_loanins_due_dat_6e0607_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['status'], name='api_loanins_status_77a461_idx'),
        ),
    ]
