# Generated by Django 5.2 on 2025-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loaninstallment_remove_payment_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='paid_ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        )
    ]
